import "@/styles/globals.css"
import { Inter } from 'next/font/google'
import { Navbar } from "@/components/Navbar/navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Outreach Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar />
          {children}
      </body>
    </html>
  )
}
