import { Navbar } from '@/components/navbar';

export const metadata = {
  title: 'The Outer Reach',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return <div><Navbar/> {children}</div>
  }